### ISSUE TITLE
Datenbankschema anlegen

### ISSUE THREAD

**Issue by KaiDoennebrink** [KaiDoennebrink/OneGrade#1]
- ER-Diagramm überprüfen (Sinn, Normalisierung)
- ER-Diagramm übertragen nach mysql (Datenbanken)
- Export des Datenbankschemas aus MySql (PHPMyAdmin) und ablegen unter Git

**Comment by tobiasguth** [comment]
Datenbank ist fertig angelegt.

[onegradeDB.zip](https://github.com/KaiDoennebrink/OneGrade/files/929194/onegradeDB.zip)
