### ISSUE TITLE
Website Design

### ISSUE THREAD

**Issue by Fresenius6000** [KaiDoennebrink/OneGrade#4]
Gesamtkonzept zur Gestaltung der Website erstellen (Visio?)

**Comment by tobiasguth** [comment]
Design der Website könnte man eventuell mit Balsamiq erstellen

**Comment by Fresenius6000** [comment]
Ich hab für die Index Seite mal was gebastelt mit dem Balsamiq Moped....müssen wir dann mal drüber talken ob die Richtung stimmt
