### ISSUE TITLE
Admin-Maske User bearbeiten

### ISSUE THREAD

**Issue by Fresenius6000** [KaiDoennebrink/OneGrade#9]
Nachdem der Admin sich die Liste aller User aufgerufen hat, soll er von dort aus User bearbeiten können.

- [ ] Hierfür muss ein Button,

- [ ] sowie ein dahinter liegender Dialog programmiert werden, bei dem der Admin die Daten ändern kann und die Bearbeitung bestätigen muss.

**Comment by KaiDoennebrink** [comment]
Wurde anders gelöst, aber Funktion ist vorhanden
